language: android

branches:
  excludes:
    - gh-pages

notifications:
  email: false

android:
  components:
    - build-tools-21.0.1
    - android-21
    - extra-android-support,extra-android-m2repository,extra-google-m2repository

before_install:
  - mvn install:install-file -Dfile=${ANDROID_HOME}/platforms/android-21/android.jar -DgroupId=android -DartifactId=android -Dversion=5.0_r1 -Dpackaging=jar -DgeneratePom=true

install:
  - "mvn package --quiet -DskipTests"
  - "mvn verify"

script: echo Tests skipped
